/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.regexdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RegexDslStandaloneSetup extends RegexDslStandaloneSetupGenerated {

	public static void doSetup() {
		new RegexDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
