/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.regexdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.ppgti.regexdsl.RegexDslRuntimeModule;
import org.ppgti.regexdsl.RegexDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RegexDslIdeSetup extends RegexDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RegexDslRuntimeModule(), new RegexDslIdeModule()));
	}
	
}
